# Generated by Django 4.2.4 on 2023-08-27 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_prod', models.CharField(max_length=150)),
                ('descricao', models.TextField(default='', max_length=500)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=7)),
                ('qtd', models.IntegerField()),
                ('imagem', models.ImageField(default='', upload_to='uploads/')),
            ],
        ),
    ]
